### PR TITLE
Update footer.html

### PR DESCRIPTION
**Pull request by maelle**
This would fix the regression observed by @cderv I think but I am missing some subtleties of why you were using this syntax.

### CODE REVIEW

**Comment by maelle** [comment]
Was it to let people override the footer?

**Comment by cderv** [comment]
let's try !

**Comment by maelle** [comment]
with pkgdown dev version there's always a footer variable passed to the footer template, it has both a left and a right component.
I am very sorry!

**Comment by cderv** [comment]
This is the same in tidytemplate FWIW: https://github.com/tidyverse/tidytemplate/blob/b819e3028b4b9342aeac238de147821bbb4c517c/inst/pkgdown/templates/footer.html#L2

**Comment by cderv** [comment]
I confirm this fix the issue. @apreshill do you know if this would be ok to change like ? 
What was it to specify a `footer` directly from the yaml file ? 
We may need that if **quillt** is to be used by others too, so that they can overwrite the footer.

**Comment by cderv** [comment]
It seems like the last change works too. This is a hidden trick from **whisker** !

**Comment by apreshill** [comment]
Should I merge this in? Is it ready for review or WIP?

**Pull request merged**
